version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bank-db
    environment:
      POSTGRES_DB: tr_bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tr_bank"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./back-transactions/tr-clientes
    container_name: bank-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tr_bank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./front-transactions
    container_name: bank-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
